language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: Zdq/tThRUUpJEQJ6wyRiuoxzmZFqN+paz6raRKXVJqedUZW2KthjugTaAM/9lWjG4INi1MiTIC08Py1QMpxVW13nJSzzZIXHlH0SesNjLPU7cMUA4rMlz35+yEjH3lhtr8cuefLj4e6T8msWnuivBd5g5KaTOgOyu5BSd1gwCARsWrvRQH0WW7qWxVmxhXvvGXhYowycOOAzm7IDhcVLrITLzn5Dn/KYX/zK3shLi+xJdcK9jlYxgIWYIjDV6Q/LGoADGT9kDDOeTgMGFuXDEXaSVR9x66f/dpGbN6I1CxTgoVG2hRM1Ro5OUMbBofpNuCRtJbKzIct6sUfYP2TFXitDc76s4w5w14MNdcIasjJ36DtOWzqurUA+dYlZ3rJXSDj78yhOZ+gWHP/n76CCZo+iWCTH2cXj+8Mb4bm4RgXIPfw/VLb5LZH54+x7mo/GlRFZreLflwQKhcpMnOLDbH2oG205H0RKjsb9QL2UCriHCA8YJW3geu4A6yaPTvowKokUtJiquDDuEKZyB4/Gvp78wcu6EH7XVfArJacRVaO4BrwLXShU+yvv9mzPiGhF4jRgs0c2zS0XLosmxzEbjXyfHT+oQI0CTx/Q1SKpv2OALY+QDlr8xuYqd/ZENogrTvlb2pw2eqWFOy8mu4JXCDxpWU8VJlRQZmdL2FBt2Hg=
